[package]
name = "async-tftp"
version = "0.2.0"
authors = ["oblique <psyberbits@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"

description = "Async TFTP implementation"
categories = ["network-programming"]
keywords = ["tftp", "tftpd", "async", "async-std"]
repository = "https://github.com/oblique/async-tftp-rs"

[dependencies]
thiserror = "1.0.9"
bytes = "0.5.3"
nom = "5.0.1"
futures = { version = "0.3.1", features = ["async-await"] }
num-derive = "0.3.0"
num-traits = "0.2.10"
async-trait = "0.1.21"
async-std = { version = "1.4.0", optional = true }
tokio = { version = "0.2.5", features = ["rt-core", "io-util", "fs", "sync", "udp", "time"], optional = true }
byteorder = "1.3.2"
log = "0.4.8"
lazy_static = "1.4.0"

[dev-dependencies]
anyhow = "1.0.25"
rand = { version = "0.7.0", features = ["small_rng"] }
md5 = "0.7.0"
tempfile = "3.1.0"
matches = "0.1.8"
simplelog = "0.7.4"
tokio = { version = "0.2", features = ["full"] }
async-std = { version = "1", features = ["unstable"] }

[features]
default = ["use-async-std"]
use-async-std = ["async-std"]
use-tokio = ["tokio"]
external-client-tests = []
