[package]
name = "tftp-rs"
version = "0.1.0"
authors = ["oblique <psyberbits@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
bytes = "0.4.12"
memchr = "2.2.0"

num-traits = "0.2"
num-derive = "0.2"
