[package]
name = "async-tftp"
version = "0.2.0"
authors = ["oblique <psyberbits@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"

description = "Async TFTP implementation"
categories = ["network-programming"]
keywords = ["tftp", "tftpd", "async", "async-std"]
repository = "https://github.com/oblique/async-tftp-rs"

[dependencies]
thiserror = "1.0.16"
bytes = "0.5.4"
nom = "5.1.1"
futures = "0.3.4"
smol = "0.1.4"
num-derive = "0.3.0"
num-traits = "0.2.11"
async-trait = "0.1.30"
log = "0.4.8"
once_cell = "1.3.1"

[dev-dependencies]
anyhow = "1.0.28"
rand = { version = "0.7.3", features = ["small_rng"] }
md5 = "0.7.0"
tempfile = "3.1.0"
matches = "0.1.8"
simplelog = "0.7.6"

[features]
external-client-tests = []
