[package]
name = "tftp"
version = "0.0.0"
authors = ["oblique <psyberbits@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
thiserror = "1.0.3"
tracing = "0.1.10"
bytes = "0.4.12"
nom = "5.0.1"
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }
num-derive = "0.3.0"
num-traits = "0.2.8"
async-trait = "0.1.16"
async-std = { version = "0.99.10", features = ["unstable"] }
byteorder = "1.3.2"

[dependencies.tracing-futures]
version = "0.1.0"
default-features = false
features = ["std-future"]

[dev-dependencies]
anyhow = "1.0.17"
rand = { version = "0.7.0", features = ["small_rng"] }
md5 = "0.6.1"
tempfile = "3.1.0"
matches = "0.1.8"
tracing-subscriber = "0.1.5"

[features]
atftp-tests = []
