[package]
name = "tftp-rs"
version = "0.1.0"
authors = ["oblique <psyberbits@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
failure = "0.1"
bytes = "0.4.12"
nom = "4.2.3"
tokio = "0.1.19"
futures = "0.1"

[dev-dependencies]
rand = "0.6.5"
