[package]
name = "tftp"
version = "0.0.0"
authors = ["oblique <psyberbits@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
failure = "0.1"
bytes = "0.4.12"
nom = "5.0.0"
futures-preview = { version = "=0.3.0-alpha.18", features = ["compat",
    "async-await", "nightly"] }
runtime = "=0.3.0-alpha.7"
futures-timer = "0.3.0"
futures-locks = "0.4.0"
matches = "0.1.8"
log = "0.4.6"
enum-primitive-derive = "0.1.2"
num-traits = "0.2.8"
async-trait = "0.1.11"

[dev-dependencies]
rand = "0.7.0"
simplelog = "0.6.0"
