[package]
name = "tftp"
version = "0.0.0"
authors = ["oblique <psyberbits@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
failure = "0.1"
bytes = "0.4.12"
nom = "4.2.3"
futures-preview = { version = "=0.3.0-alpha.16", features = ["compat"] }
runtime = "=0.3.0-alpha.4"
futures-timer = "0.1"

[dev-dependencies]
rand = "0.6.5"
